### ISSUE TITLE
Protect code

### ISSUE THREAD

**Issue by jabrena** [jabrena/cf-nodejs-client#6]
It is necessary to avoid this kind of errors:

```

undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (C:\Users\PATH\cf-nodejs-client\lib\utils\HttpUtils.js:76:31)
    at self.callback (C:\Users\PATH\cf-nodejs-client\node_modules\request\request.js:198:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (C:\Users\PATH\cf-nodejs-client\node_modules\request\request.js:861:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:950:16
    at process._tickCallback (node.js:355:11)

```

**Comment by jabrena** [comment]
Fixed
